version: "3.8"

services:
  app:
    image: thankrain/timespeak:latest
    container_name: timespeak_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      - CONFIG_FILE=/app/env/example.yaml
    volumes:
      - ./env:/app/env
      - ./data/storage:/app/data/storage
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - mongo
      - redis
    networks:
      - timespeak
  mongo:
    image: mongo:5.0.2
    volumes:
      - ./data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_DATABASE=timespeak
    container_name: timespeak_dev_mongo
    restart: always
    expose:
      - "27017"
    networks:
      - timespeak
  redis:
    image: redis:6.2.5
    expose:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: timespeak_dev_redis
    volumes:
      - ./data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - timespeak
networks:
  timespeak:
    driver: bridge