package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"time_speak_server/graph/generated"
	"time_speak_server/src/service/mail"

	"go.mongodb.org/mongo-driver/mongo"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input generated.RegisterInput) (string, error) {
	if r.mailSvc.CheckEmailVerifyCode(ctx, input.Email, input.EmailVerifyCode) {
		_, err := r.userSvc.GetUserByMail(ctx, input.Email)
		if err != nil {
			if err == mongo.ErrNoDocuments {
				// 未注册
				id, err := r.userSvc.AddUser(ctx, input.Username, input.Password, input.Email)
				if err != nil {
					return "", err
				}
				return id.Hex(), nil
			} else {
				return "", err
			}
		}
		return "", errMailOccupied
	}
	return "", errVerifyCodeWrong
}

// SendEmailCode is the resolver for the sendEmailCode field.
func (r *mutationResolver) SendEmailCode(ctx context.Context, input generated.SendEmailCodeInput) (bool, error) {
	err := r.mailSvc.NewEmailVerifyCode(ctx, input.Mail)
	if err != nil {
		if err == mail.ErrVerifyCodeCoolDown {
			return false, errTooManyRequest
		} else {
			return false, internalError(err)
		}
	}
	return true, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input generated.LoginInput) (*generated.LoginPayload, error) {
	match, err := r.userSvc.CheckPasswordByUsername(ctx, input.Username, input.Password)
	if err != nil {
		return nil, internalError(err)
	}
	if !match {
		return nil, errUsernameOrPasswordWrong
	}

	jwt, token, err := r.userSvc.GetTokenByUsername(ctx, input.Username)
	if err != nil {
		return nil, internalError(err)
	}

	return &generated.LoginPayload{
		ID:         jwt.ID,
		Token:      token,
		Expire:     jwt.ExpiresAt,
		Permission: jwt.Permission,
	}, nil
}
