package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"
	"time_speak_server/graph/generated"
)

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, input generated.CommentInput) (string, error) {
	panic(fmt.Errorf("not implemented: AddComment - addComment"))
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, input generated.CommentInput) (bool, error) {
	panic(fmt.Errorf("not implemented: UpdateComment - updateComment"))
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, input string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteComment - deleteComment"))
}

// AllComments is the resolver for the allComments field.
func (r *queryResolver) AllComments(ctx context.Context, id string, page int, size int, desc bool) ([]*generated.Comment, error) {
	panic(fmt.Errorf("not implemented: AllComments - allComments"))
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, input string) ([]*generated.Comment, error) {
	panic(fmt.Errorf("not implemented: Comments - comments"))
}
