package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"
	"time_speak_server/graph/generated"
)

// AllHistories is the resolver for the allHistories field.
func (r *queryResolver) AllHistories(ctx context.Context, id string, page int, size int) ([]*generated.History, error) {
	panic(fmt.Errorf("not implemented: AllHistories - allHistories"))
}
