package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"
	"time_speak_server/graph/generated"
)

// AddMemory is the resolver for the addMemory field.
func (r *mutationResolver) AddMemory(ctx context.Context, input generated.AddMemoryInput) (string, error) {
	panic(fmt.Errorf("not implemented: AddMemory - addMemory"))
}

// UpdateMemory is the resolver for the updateMemory field.
func (r *mutationResolver) UpdateMemory(ctx context.Context, input generated.AddMemoryInput) (bool, error) {
	panic(fmt.Errorf("not implemented: UpdateMemory - updateMemory"))
}

// ArchiveMemory is the resolver for the archiveMemory field.
func (r *mutationResolver) ArchiveMemory(ctx context.Context, input string) (bool, error) {
	panic(fmt.Errorf("not implemented: ArchiveMemory - archiveMemory"))
}

// DeleteMemory is the resolver for the deleteMemory field.
func (r *mutationResolver) DeleteMemory(ctx context.Context, input string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteMemory - deleteMemory"))
}

// AllMemories is the resolver for the allMemories field.
func (r *queryResolver) AllMemories(ctx context.Context, page int, size int, desc bool) ([]*generated.Memory, error) {
	panic(fmt.Errorf("not implemented: AllMemories - allMemories"))
}

// AllMemoriesByCreated is the resolver for the allMemoriesByCreated field.
func (r *queryResolver) AllMemoriesByCreated(ctx context.Context, page int, size int, desc bool) ([]*generated.Memory, error) {
	panic(fmt.Errorf("not implemented: AllMemoriesByCreated - allMemoriesByCreated"))
}

// ArchivedMemories is the resolver for the archivedMemories field.
func (r *queryResolver) ArchivedMemories(ctx context.Context, page int, size int, desc bool) ([]*generated.Memory, error) {
	panic(fmt.Errorf("not implemented: ArchivedMemories - archivedMemories"))
}

// Memory is the resolver for the memory field.
func (r *queryResolver) Memory(ctx context.Context, input string) (*generated.Memory, error) {
	panic(fmt.Errorf("not implemented: Memory - memory"))
}
