package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"
	"time_speak_server/graph/generated"
)

// AddResource is the resolver for the addResource field.
func (r *mutationResolver) AddResource(ctx context.Context, input generated.ResourceInput) (*generated.UploadTokenPayload, error) {
	panic(fmt.Errorf("not implemented: AddResource - addResource"))
}

// ArchiveResource is the resolver for the archiveResource field.
func (r *mutationResolver) ArchiveResource(ctx context.Context, input string) (bool, error) {
	panic(fmt.Errorf("not implemented: ArchiveResource - archiveResource"))
}

// DeleteResource is the resolver for the deleteResource field.
func (r *mutationResolver) DeleteResource(ctx context.Context, input string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteResource - deleteResource"))
}

// AllResources is the resolver for the allResources field.
func (r *queryResolver) AllResources(ctx context.Context, page int, size int, desc bool) ([]*generated.Resource, error) {
	panic(fmt.Errorf("not implemented: AllResources - allResources"))
}
