package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"time_speak_server/graph/generated"
	"time_speak_server/src/config"
)

// Status is the resolver for the status field.
func (r *queryResolver) Status(ctx context.Context) (*generated.ServerStatus, error) {
	return &generated.ServerStatus{
		VersionCode:     config.VersionCode,
		VersionName:     config.VersionName,
		StorageProvider: r.conf.Storage.StorageProvider,
	}, nil
}
