package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"time_speak_server/graph/generated"
	"time_speak_server/src/service/subscribe"
	"time_speak_server/src/service/user"
)

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*user.User, error) {
	uid, err := user.GetUserFromJwt(ctx)
	if err != nil {
		return nil, err
	}
	getUser, err := r.userSvc.GetUser(ctx, uid)
	if err != nil {
		return nil, err
	}
	return &getUser, nil
}

// Used is the resolver for the used field.
func (r *userResolver) Used(ctx context.Context, obj *user.User) (int64, error) {
	used, err := r.resourceSvc.GetResourceUsed(ctx, obj.ObjectID)
	if err != nil {
		return 0, err
	}
	return used, nil
}

// Subscribe is the resolver for the subscribe field.
func (r *userResolver) Subscribe(ctx context.Context, obj *user.User) (*subscribe.Subscribe, error) {
	getSubscribe, err := r.subscribeSvc.GetSubscribe(ctx, obj.Subscribe)
	if err != nil {
		return nil, err
	}
	return getSubscribe, nil
}

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
