package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"
	"time_speak_server/graph/generated"
	"time_speak_server/src/service/mail"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input generated.RegisterInput) (*generated.RegisterPayload, error) {
	panic(fmt.Errorf("not implemented: Register - register"))
}

// SendEmailCode is the resolver for the sendEmailCode field.
func (r *mutationResolver) SendEmailCode(ctx context.Context, input generated.SendEmailCodeInput) (*generated.SendCodePayload, error) {
	err := r.mailSvc.NewEmailVerifyCode(ctx, input.Mail)
	if err != nil {
		if err == mail.ErrVerifyCodeCoolDown {
			return nil, errTooManyRequest
		} else {
			return nil, internalError(err)
		}
	}
	return &generated.SendCodePayload{
		Success: true,
	}, nil
}

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, input generated.LoginInput) (*generated.LoginPayload, error) {
	match, err := r.userSvc.CheckPasswordByUsername(ctx, input.Username, input.Password)
	if err != nil {
		return nil, internalError(err)
	}
	if !match {
		return nil, errUsernameOrPasswordWrong
	}

	jwt, token, err := r.userSvc.GetTokenByUsername(ctx, input.Username)
	if err != nil {
		return nil, internalError(err)
	}

	return &generated.LoginPayload{
		ID:         jwt.ID,
		Token:      token,
		Expire:     jwt.ExpiresAt,
		Permission: jwt.Permission,
	}, nil
}
